name: PR Stats

on:
  workflow_dispatch:
jobs:
  pr-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: PR Stats
        uses: "naver/pr-stats@v1.0.0"
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}
          period: "2024-01-01~"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
